package com.hanielcota.essentials.modules.homes.menu.presentation;

import java.util.EnumMap;
import java.util.Locale;
import java.util.Map;
import lombok.AccessLevel;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import org.bukkit.Material;

/** Display helpers for {@link Material} — kept tiny and pure so the menu code can stay lean. */
@NoArgsConstructor(access = AccessLevel.PRIVATE)
final class MaterialNames {

  private static final Map<Material, String> NAMES = buildNames();

  static String pretty(@NonNull Material material) {
    var translated = NAMES.get(material);
    if (translated != null) {
      return translated;
    }
    return material.name().toLowerCase(Locale.ROOT).replace('_', ' ');
  }

  private static Map<Material, String> buildNames() {
    var map = new EnumMap<Material, String>(Material.class);

    // Construction
    map.put(Material.STONE, "Pedra");
    map.put(Material.COBBLESTONE, "Paralelepípedo");
    map.put(Material.MOSSY_COBBLESTONE, "Paralelepípedo com musgo");
    map.put(Material.SMOOTH_STONE, "Pedra lisa");
    map.put(Material.GRANITE, "Granito");
    map.put(Material.POLISHED_GRANITE, "Granito polido");
    map.put(Material.DIORITE, "Diorito");
    map.put(Material.POLISHED_DIORITE, "Diorito polido");
    map.put(Material.ANDESITE, "Andesito");
    map.put(Material.POLISHED_ANDESITE, "Andesito polido");
    map.put(Material.DEEPSLATE, "Ardósia profunda");
    map.put(Material.COBBLED_DEEPSLATE, "Ardósia profunda comum");
    map.put(Material.POLISHED_DEEPSLATE, "Ardósia profunda polida");
    map.put(Material.REINFORCED_DEEPSLATE, "Ardósia profunda reforçada");
    map.put(Material.TUFF, "Tufo");
    map.put(Material.POLISHED_TUFF, "Tufo polido");
    map.put(Material.BRICKS, "Tijolos");
    map.put(Material.STONE_BRICKS, "Tijolos de pedra");
    map.put(Material.MOSSY_STONE_BRICKS, "Tijolos de pedra com musgo");
    map.put(Material.CRACKED_STONE_BRICKS, "Tijolos de pedra rachados");
    map.put(Material.DEEPSLATE_BRICKS, "Tijolos de ardósia profunda");
    map.put(Material.DEEPSLATE_TILES, "Ladrilhos de ardósia profunda");
    map.put(Material.END_STONE_BRICKS, "Tijolos de pedra do End");
    map.put(Material.NETHER_BRICKS, "Tijolos do Nether");
    map.put(Material.RED_NETHER_BRICKS, "Tijolos vermelhos do Nether");
    map.put(Material.PRISMARINE_BRICKS, "Tijolos de prismarinha");
    map.put(Material.MUD_BRICKS, "Tijolos de lama");
    map.put(Material.RESIN_BRICKS, "Tijolos de resina");
    map.put(Material.PACKED_MUD, "Lama compactada");
    map.put(Material.SANDSTONE, "Arenito");
    map.put(Material.CUT_SANDSTONE, "Arenito cortado");
    map.put(Material.SMOOTH_SANDSTONE, "Arenito liso");
    map.put(Material.RED_SANDSTONE, "Arenito vermelho");
    map.put(Material.CUT_RED_SANDSTONE, "Arenito vermelho cortado");
    map.put(Material.SMOOTH_RED_SANDSTONE, "Arenito vermelho liso");
    map.put(Material.QUARTZ_BLOCK, "Bloco de quartzo");
    map.put(Material.SMOOTH_QUARTZ, "Quartzo liso");
    map.put(Material.QUARTZ_BRICKS, "Tijolos de quartzo");
    map.put(Material.QUARTZ_PILLAR, "Pilar de quartzo");
    map.put(Material.CHISELED_QUARTZ_BLOCK, "Bloco de quartzo cinzelado");
    map.put(Material.COPPER_BLOCK, "Bloco de cobre");
    map.put(Material.EXPOSED_COPPER, "Cobre exposto");
    map.put(Material.WEATHERED_COPPER, "Cobre envelhecido");
    map.put(Material.OXIDIZED_COPPER, "Cobre oxidado");
    map.put(Material.CUT_COPPER, "Cobre cortado");
    map.put(Material.EXPOSED_CUT_COPPER, "Cobre exposto cortado");
    map.put(Material.WEATHERED_CUT_COPPER, "Cobre envelhecido cortado");
    map.put(Material.OXIDIZED_CUT_COPPER, "Cobre oxidado cortado");
    map.put(Material.WAXED_COPPER_BLOCK, "Bloco de cobre encerado");
    map.put(Material.WAXED_EXPOSED_COPPER, "Cobre exposto encerado");
    map.put(Material.WAXED_WEATHERED_COPPER, "Cobre envelhecido encerado");
    map.put(Material.WAXED_OXIDIZED_COPPER, "Cobre oxidado encerado");
    map.put(Material.WAXED_CUT_COPPER, "Cobre cortado encerado");
    map.put(Material.WAXED_EXPOSED_CUT_COPPER, "Cobre exposto cortado encerado");
    map.put(Material.WAXED_WEATHERED_CUT_COPPER, "Cobre envelhecido cortado encerado");
    map.put(Material.WAXED_OXIDIZED_CUT_COPPER, "Cobre oxidado cortado encerado");

    // Wood
    map.put(Material.OAK_LOG, "Tronco de carvalho");
    map.put(Material.SPRUCE_LOG, "Tronco de pinheiro");
    map.put(Material.BIRCH_LOG, "Tronco de vidoeiro");
    map.put(Material.JUNGLE_LOG, "Tronco de selva");
    map.put(Material.ACACIA_LOG, "Tronco de acácia");
    map.put(Material.DARK_OAK_LOG, "Tronco de carvalho escuro");
    map.put(Material.MANGROVE_LOG, "Tronco de mangue");
    map.put(Material.CHERRY_LOG, "Tronco de cerejeira");
    map.put(Material.PALE_OAK_LOG, "Tronco de carvalho pálido");
    map.put(Material.STRIPPED_OAK_LOG, "Tronco de carvalho descascado");
    map.put(Material.STRIPPED_SPRUCE_LOG, "Tronco de pinheiro descascado");
    map.put(Material.STRIPPED_BIRCH_LOG, "Tronco de vidoeiro descascado");
    map.put(Material.STRIPPED_JUNGLE_LOG, "Tronco de selva descascado");
    map.put(Material.STRIPPED_ACACIA_LOG, "Tronco de acácia descascado");
    map.put(Material.STRIPPED_DARK_OAK_LOG, "Tronco de carvalho escuro descascado");
    map.put(Material.STRIPPED_MANGROVE_LOG, "Tronco de mangue descascado");
    map.put(Material.STRIPPED_CHERRY_LOG, "Tronco de cerejeira descascado");
    map.put(Material.STRIPPED_PALE_OAK_LOG, "Tronco de carvalho pálido descascado");
    map.put(Material.OAK_PLANKS, "Tábua de carvalho");
    map.put(Material.SPRUCE_PLANKS, "Tábua de pinheiro");
    map.put(Material.BIRCH_PLANKS, "Tábua de vidoeiro");
    map.put(Material.JUNGLE_PLANKS, "Tábua de selva");
    map.put(Material.ACACIA_PLANKS, "Tábua de acácia");
    map.put(Material.DARK_OAK_PLANKS, "Tábua de carvalho escuro");
    map.put(Material.MANGROVE_PLANKS, "Tábua de mangue");
    map.put(Material.CHERRY_PLANKS, "Tábua de cerejeira");
    map.put(Material.PALE_OAK_PLANKS, "Tábua de carvalho pálido");
    map.put(Material.BAMBOO_PLANKS, "Tábua de bambu");
    map.put(Material.BAMBOO_MOSAIC, "Mosaico de bambu");
    map.put(Material.OAK_WOOD, "Madeira de carvalho");
    map.put(Material.SPRUCE_WOOD, "Madeira de pinheiro");
    map.put(Material.BIRCH_WOOD, "Madeira de vidoeiro");
    map.put(Material.JUNGLE_WOOD, "Madeira de selva");
    map.put(Material.ACACIA_WOOD, "Madeira de acácia");
    map.put(Material.DARK_OAK_WOOD, "Madeira de carvalho escuro");
    map.put(Material.MANGROVE_WOOD, "Madeira de mangue");
    map.put(Material.CHERRY_WOOD, "Madeira de cerejeira");
    map.put(Material.PALE_OAK_WOOD, "Madeira de carvalho pálido");
    map.put(Material.BAMBOO_BLOCK, "Bloco de bambu");

    // Decoration
    map.put(Material.WHITE_WOOL, "Lã branca");
    map.put(Material.ORANGE_WOOL, "Lã laranja");
    map.put(Material.MAGENTA_WOOL, "Lã magenta");
    map.put(Material.LIGHT_BLUE_WOOL, "Lã azul-claro");
    map.put(Material.YELLOW_WOOL, "Lã amarela");
    map.put(Material.LIME_WOOL, "Lã verde-limão");
    map.put(Material.PINK_WOOL, "Lã rosa");
    map.put(Material.GRAY_WOOL, "Lã cinza");
    map.put(Material.LIGHT_GRAY_WOOL, "Lã cinza-claro");
    map.put(Material.CYAN_WOOL, "Lã ciano");
    map.put(Material.PURPLE_WOOL, "Lã roxa");
    map.put(Material.BLUE_WOOL, "Lã azul");
    map.put(Material.BROWN_WOOL, "Lã marrom");
    map.put(Material.GREEN_WOOL, "Lã verde");
    map.put(Material.RED_WOOL, "Lã vermelha");
    map.put(Material.BLACK_WOOL, "Lã preta");
    map.put(Material.WHITE_CARPET, "Tapete branco");
    map.put(Material.ORANGE_CARPET, "Tapete laranja");
    map.put(Material.MAGENTA_CARPET, "Tapete magenta");
    map.put(Material.LIGHT_BLUE_CARPET, "Tapete azul-claro");
    map.put(Material.YELLOW_CARPET, "Tapete amarelo");
    map.put(Material.LIME_CARPET, "Tapete verde-limão");
    map.put(Material.PINK_CARPET, "Tapete rosa");
    map.put(Material.GRAY_CARPET, "Tapete cinza");
    map.put(Material.LIGHT_GRAY_CARPET, "Tapete cinza-claro");
    map.put(Material.CYAN_CARPET, "Tapete ciano");
    map.put(Material.PURPLE_CARPET, "Tapete roxo");
    map.put(Material.BLUE_CARPET, "Tapete azul");
    map.put(Material.BROWN_CARPET, "Tapete marrom");
    map.put(Material.GREEN_CARPET, "Tapete verde");
    map.put(Material.RED_CARPET, "Tapete vermelho");
    map.put(Material.BLACK_CARPET, "Tapete preto");
    map.put(Material.TERRACOTTA, "Terracota");
    map.put(Material.WHITE_TERRACOTTA, "Terracota branca");
    map.put(Material.ORANGE_TERRACOTTA, "Terracota laranja");
    map.put(Material.MAGENTA_TERRACOTTA, "Terracota magenta");
    map.put(Material.LIGHT_BLUE_TERRACOTTA, "Terracota azul-claro");
    map.put(Material.YELLOW_TERRACOTTA, "Terracota amarela");
    map.put(Material.LIME_TERRACOTTA, "Terracota verde-limão");
    map.put(Material.PINK_TERRACOTTA, "Terracota rosa");
    map.put(Material.GRAY_TERRACOTTA, "Terracota cinza");
    map.put(Material.LIGHT_GRAY_TERRACOTTA, "Terracota cinza-claro");
    map.put(Material.CYAN_TERRACOTTA, "Terracota ciano");
    map.put(Material.PURPLE_TERRACOTTA, "Terracota roxa");
    map.put(Material.BLUE_TERRACOTTA, "Terracota azul");
    map.put(Material.BROWN_TERRACOTTA, "Terracota marrom");
    map.put(Material.GREEN_TERRACOTTA, "Terracota verde");
    map.put(Material.RED_TERRACOTTA, "Terracota vermelha");
    map.put(Material.BLACK_TERRACOTTA, "Terracota preta");
    map.put(Material.WHITE_GLAZED_TERRACOTTA, "Terracota esmaltada branca");
    map.put(Material.ORANGE_GLAZED_TERRACOTTA, "Terracota esmaltada laranja");
    map.put(Material.MAGENTA_GLAZED_TERRACOTTA, "Terracota esmaltada magenta");
    map.put(Material.LIGHT_BLUE_GLAZED_TERRACOTTA, "Terracota esmaltada azul-claro");
    map.put(Material.YELLOW_GLAZED_TERRACOTTA, "Terracota esmaltada amarela");
    map.put(Material.LIME_GLAZED_TERRACOTTA, "Terracota esmaltada verde-limão");
    map.put(Material.PINK_GLAZED_TERRACOTTA, "Terracota esmaltada rosa");
    map.put(Material.GRAY_GLAZED_TERRACOTTA, "Terracota esmaltada cinza");
    map.put(Material.LIGHT_GRAY_GLAZED_TERRACOTTA, "Terracota esmaltada cinza-claro");
    map.put(Material.CYAN_GLAZED_TERRACOTTA, "Terracota esmaltada ciano");
    map.put(Material.PURPLE_GLAZED_TERRACOTTA, "Terracota esmaltada roxa");
    map.put(Material.BLUE_GLAZED_TERRACOTTA, "Terracota esmaltada azul");
    map.put(Material.BROWN_GLAZED_TERRACOTTA, "Terracota esmaltada marrom");
    map.put(Material.GREEN_GLAZED_TERRACOTTA, "Terracota esmaltada verde");
    map.put(Material.RED_GLAZED_TERRACOTTA, "Terracota esmaltada vermelha");
    map.put(Material.BLACK_GLAZED_TERRACOTTA, "Terracota esmaltada preta");
    map.put(Material.WHITE_CONCRETE, "Concreto branco");
    map.put(Material.ORANGE_CONCRETE, "Concreto laranja");
    map.put(Material.MAGENTA_CONCRETE, "Concreto magenta");
    map.put(Material.LIGHT_BLUE_CONCRETE, "Concreto azul-claro");
    map.put(Material.YELLOW_CONCRETE, "Concreto amarelo");
    map.put(Material.LIME_CONCRETE, "Concreto verde-limão");
    map.put(Material.PINK_CONCRETE, "Concreto rosa");
    map.put(Material.GRAY_CONCRETE, "Concreto cinza");
    map.put(Material.LIGHT_GRAY_CONCRETE, "Concreto cinza-claro");
    map.put(Material.CYAN_CONCRETE, "Concreto ciano");
    map.put(Material.PURPLE_CONCRETE, "Concreto roxo");
    map.put(Material.BLUE_CONCRETE, "Concreto azul");
    map.put(Material.BROWN_CONCRETE, "Concreto marrom");
    map.put(Material.GREEN_CONCRETE, "Concreto verde");
    map.put(Material.RED_CONCRETE, "Concreto vermelho");
    map.put(Material.BLACK_CONCRETE, "Concreto preto");
    map.put(Material.GLASS, "Vidro");
    map.put(Material.WHITE_STAINED_GLASS, "Vidro pintado branco");
    map.put(Material.ORANGE_STAINED_GLASS, "Vidro pintado laranja");
    map.put(Material.MAGENTA_STAINED_GLASS, "Vidro pintado magenta");
    map.put(Material.LIGHT_BLUE_STAINED_GLASS, "Vidro pintado azul-claro");
    map.put(Material.YELLOW_STAINED_GLASS, "Vidro pintado amarelo");
    map.put(Material.LIME_STAINED_GLASS, "Vidro pintado verde-limão");
    map.put(Material.PINK_STAINED_GLASS, "Vidro pintado rosa");
    map.put(Material.GRAY_STAINED_GLASS, "Vidro pintado cinza");
    map.put(Material.LIGHT_GRAY_STAINED_GLASS, "Vidro pintado cinza-claro");
    map.put(Material.CYAN_STAINED_GLASS, "Vidro pintado ciano");
    map.put(Material.PURPLE_STAINED_GLASS, "Vidro pintado roxo");
    map.put(Material.BLUE_STAINED_GLASS, "Vidro pintado azul");
    map.put(Material.BROWN_STAINED_GLASS, "Vidro pintado marrom");
    map.put(Material.GREEN_STAINED_GLASS, "Vidro pintado verde");
    map.put(Material.RED_STAINED_GLASS, "Vidro pintado vermelho");
    map.put(Material.BLACK_STAINED_GLASS, "Vidro pintado preto");

    // Lighting
    map.put(Material.TORCH, "Tocha");
    map.put(Material.SOUL_TORCH, "Tocha da alma");
    map.put(Material.REDSTONE_TORCH, "Tocha de redstone");
    map.put(Material.LANTERN, "Lanterna");
    map.put(Material.SOUL_LANTERN, "Lanterna da alma");
    map.put(Material.SEA_LANTERN, "Lanterna do mar");
    map.put(Material.JACK_O_LANTERN, "Abóbora iluminada");
    map.put(Material.SHROOMLIGHT, "Luz de cogumelo");
    map.put(Material.OCHRE_FROGLIGHT, "Luz de sapo ocre");
    map.put(Material.VERDANT_FROGLIGHT, "Luz de sapo verde");
    map.put(Material.PEARLESCENT_FROGLIGHT, "Luz de sapo perolada");
    map.put(Material.CAMPFIRE, "Fogueira");
    map.put(Material.SOUL_CAMPFIRE, "Fogueira da alma");
    map.put(Material.CANDLE, "Vela");
    map.put(Material.WHITE_CANDLE, "Vela branca");
    map.put(Material.ORANGE_CANDLE, "Vela laranja");
    map.put(Material.MAGENTA_CANDLE, "Vela magenta");
    map.put(Material.LIGHT_BLUE_CANDLE, "Vela azul-claro");
    map.put(Material.YELLOW_CANDLE, "Vela amarela");
    map.put(Material.LIME_CANDLE, "Vela verde-limão");
    map.put(Material.PINK_CANDLE, "Vela rosa");
    map.put(Material.GRAY_CANDLE, "Vela cinza");
    map.put(Material.LIGHT_GRAY_CANDLE, "Vela cinza-claro");
    map.put(Material.CYAN_CANDLE, "Vela ciano");
    map.put(Material.PURPLE_CANDLE, "Vela roxa");
    map.put(Material.BLUE_CANDLE, "Vela azul");
    map.put(Material.BROWN_CANDLE, "Vela marrom");
    map.put(Material.GREEN_CANDLE, "Vela verde");
    map.put(Material.RED_CANDLE, "Vela vermelha");
    map.put(Material.BLACK_CANDLE, "Vela preta");

    // Combat
    map.put(Material.WOODEN_SWORD, "Espada de madeira");
    map.put(Material.STONE_SWORD, "Espada de pedra");
    map.put(Material.IRON_SWORD, "Espada de ferro");
    map.put(Material.GOLDEN_SWORD, "Espada de ouro");
    map.put(Material.DIAMOND_SWORD, "Espada de diamante");
    map.put(Material.NETHERITE_SWORD, "Espada de netherite");
    map.put(Material.WOODEN_AXE, "Machado de madeira");
    map.put(Material.STONE_AXE, "Machado de pedra");
    map.put(Material.IRON_AXE, "Machado de ferro");
    map.put(Material.GOLDEN_AXE, "Machado de ouro");
    map.put(Material.DIAMOND_AXE, "Machado de diamante");
    map.put(Material.NETHERITE_AXE, "Machado de netherite");
    map.put(Material.BOW, "Arco");
    map.put(Material.CROSSBOW, "Besta");
    map.put(Material.TRIDENT, "Tridente");
    map.put(Material.ARROW, "Flecha");
    map.put(Material.SPECTRAL_ARROW, "Flecha espectral");
    map.put(Material.TIPPED_ARROW, "Flecha com poção");
    map.put(Material.SHIELD, "Escudo");
    map.put(Material.TOTEM_OF_UNDYING, "Totem da imortalidade");
    map.put(Material.LEATHER_HELMET, "Capacete de couro");
    map.put(Material.LEATHER_CHESTPLATE, "Peitoral de couro");
    map.put(Material.LEATHER_LEGGINGS, "Calças de couro");
    map.put(Material.LEATHER_BOOTS, "Botas de couro");
    map.put(Material.CHAINMAIL_HELMET, "Capacete de cota de malha");
    map.put(Material.CHAINMAIL_CHESTPLATE, "Peitoral de cota de malha");
    map.put(Material.CHAINMAIL_LEGGINGS, "Calças de cota de malha");
    map.put(Material.CHAINMAIL_BOOTS, "Botas de cota de malha");
    map.put(Material.IRON_HELMET, "Capacete de ferro");
    map.put(Material.IRON_CHESTPLATE, "Peitoral de ferro");
    map.put(Material.IRON_LEGGINGS, "Calças de ferro");
    map.put(Material.IRON_BOOTS, "Botas de ferro");
    map.put(Material.GOLDEN_HELMET, "Capacete de ouro");
    map.put(Material.GOLDEN_CHESTPLATE, "Peitoral de ouro");
    map.put(Material.GOLDEN_LEGGINGS, "Calças de ouro");
    map.put(Material.GOLDEN_BOOTS, "Botas de ouro");
    map.put(Material.DIAMOND_HELMET, "Capacete de diamante");
    map.put(Material.DIAMOND_CHESTPLATE, "Peitoral de diamante");
    map.put(Material.DIAMOND_LEGGINGS, "Calças de diamante");
    map.put(Material.DIAMOND_BOOTS, "Botas de diamante");
    map.put(Material.NETHERITE_HELMET, "Capacete de netherite");
    map.put(Material.NETHERITE_CHESTPLATE, "Peitoral de netherite");
    map.put(Material.NETHERITE_LEGGINGS, "Calças de netherite");
    map.put(Material.NETHERITE_BOOTS, "Botas de netherite");
    map.put(Material.TURTLE_HELMET, "Capacete de tartaruga");
    map.put(Material.WOLF_ARMOR, "Armadura de lobo");

    // Tools
    map.put(Material.WOODEN_PICKAXE, "Picareta de madeira");
    map.put(Material.STONE_PICKAXE, "Picareta de pedra");
    map.put(Material.IRON_PICKAXE, "Picareta de ferro");
    map.put(Material.GOLDEN_PICKAXE, "Picareta de ouro");
    map.put(Material.DIAMOND_PICKAXE, "Picareta de diamante");
    map.put(Material.NETHERITE_PICKAXE, "Picareta de netherite");
    map.put(Material.WOODEN_SHOVEL, "Pá de madeira");
    map.put(Material.STONE_SHOVEL, "Pá de pedra");
    map.put(Material.IRON_SHOVEL, "Pá de ferro");
    map.put(Material.GOLDEN_SHOVEL, "Pá de ouro");
    map.put(Material.DIAMOND_SHOVEL, "Pá de diamante");
    map.put(Material.NETHERITE_SHOVEL, "Pá de netherite");
    map.put(Material.WOODEN_HOE, "Enxada de madeira");
    map.put(Material.STONE_HOE, "Enxada de pedra");
    map.put(Material.IRON_HOE, "Enxada de ferro");
    map.put(Material.GOLDEN_HOE, "Enxada de ouro");
    map.put(Material.DIAMOND_HOE, "Enxada de diamante");
    map.put(Material.NETHERITE_HOE, "Enxada de netherite");
    map.put(Material.SHEARS, "Tesoura");
    map.put(Material.FLINT_AND_STEEL, "Pederneira");
    map.put(Material.FISHING_ROD, "Vara de pesca");
    map.put(Material.CARROT_ON_A_STICK, "Cenoura numa vara");
    map.put(Material.WARPED_FUNGUS_ON_A_STICK, "Fungo distorcido numa vara");
    map.put(Material.BRUSH, "Pincel");
    map.put(Material.SPYGLASS, "Luneta");
    map.put(Material.LEAD, "Corda");
    map.put(Material.NAME_TAG, "Etiqueta de nome");
    map.put(Material.SADDLE, "Sela");
    map.put(Material.COMPASS, "Bússola");
    map.put(Material.RECOVERY_COMPASS, "Bússola de recuperação");
    map.put(Material.CLOCK, "Relógio");
    map.put(Material.MAP, "Mapa");
    map.put(Material.FILLED_MAP, "Mapa preenchido");

    // Minerals
    map.put(Material.COAL, "Carvão");
    map.put(Material.CHARCOAL, "Carvão vegetal");
    map.put(Material.IRON_INGOT, "Lingote de ferro");
    map.put(Material.GOLD_INGOT, "Lingote de ouro");
    map.put(Material.COPPER_INGOT, "Lingote de cobre");
    map.put(Material.NETHERITE_INGOT, "Lingote de netherite");
    map.put(Material.REDSTONE, "Redstone");
    map.put(Material.LAPIS_LAZULI, "Lápis-lazúli");
    map.put(Material.DIAMOND, "Diamante");
    map.put(Material.EMERALD, "Esmeralda");
    map.put(Material.QUARTZ, "Quartzo");
    map.put(Material.AMETHYST_SHARD, "Fragmento de ametista");
    map.put(Material.RAW_IRON, "Ferro bruto");
    map.put(Material.RAW_GOLD, "Ouro bruto");
    map.put(Material.RAW_COPPER, "Cobre bruto");
    map.put(Material.IRON_NUGGET, "Pepita de ferro");
    map.put(Material.GOLD_NUGGET, "Pepita de ouro");
    map.put(Material.NETHERITE_SCRAP, "Sucata de netherite");
    map.put(Material.COAL_BLOCK, "Bloco de carvão");
    map.put(Material.IRON_BLOCK, "Bloco de ferro");
    map.put(Material.GOLD_BLOCK, "Bloco de ouro");
    map.put(Material.REDSTONE_BLOCK, "Bloco de redstone");
    map.put(Material.LAPIS_BLOCK, "Bloco de lápis-lazúli");
    map.put(Material.DIAMOND_BLOCK, "Bloco de diamante");
    map.put(Material.EMERALD_BLOCK, "Bloco de esmeralda");
    map.put(Material.NETHERITE_BLOCK, "Bloco de netherite");
    map.put(Material.AMETHYST_BLOCK, "Bloco de ametista");
    map.put(Material.BUDDING_AMETHYST, "Ametista em formação");
    map.put(Material.SMALL_AMETHYST_BUD, "Botão pequeno de ametista");
    map.put(Material.MEDIUM_AMETHYST_BUD, "Botão médio de ametista");
    map.put(Material.LARGE_AMETHYST_BUD, "Botão grande de ametista");
    map.put(Material.AMETHYST_CLUSTER, "Aglomerado de ametista");

    // Redstone
    map.put(Material.REDSTONE_WIRE, "Fio de redstone");
    map.put(Material.REPEATER, "Repetidor");
    map.put(Material.COMPARATOR, "Comparador");
    map.put(Material.PISTON, "Pistão");
    map.put(Material.STICKY_PISTON, "Pistão pegajoso");
    map.put(Material.SLIME_BLOCK, "Bloco de slime");
    map.put(Material.HONEY_BLOCK, "Bloco de mel");
    map.put(Material.OBSERVER, "Observador");
    map.put(Material.DISPENSER, "Distribuidor");
    map.put(Material.DROPPER, "Dropador");
    map.put(Material.HOPPER, "Funil");
    map.put(Material.CHEST, "Baú");
    map.put(Material.TRAPPED_CHEST, "Baú armadilha");
    map.put(Material.BARREL, "Barril");
    map.put(Material.FURNACE, "Fornalha");
    map.put(Material.BLAST_FURNACE, "Alto-forno");
    map.put(Material.SMOKER, "Defumador");
    map.put(Material.DAYLIGHT_DETECTOR, "Detector de luz solar");
    map.put(Material.LECTERN, "Estante para livros");
    map.put(Material.NOTE_BLOCK, "Bloco de nota");
    map.put(Material.JUKEBOX, "Jukebox");
    map.put(Material.BELL, "Sino");
    map.put(Material.TRIPWIRE_HOOK, "Gancho de fio de viagem");
    map.put(Material.STRING, "Fio");
    map.put(Material.LEVER, "Alavanca");
    map.put(Material.STONE_BUTTON, "Botão de pedra");
    map.put(Material.OAK_BUTTON, "Botão de carvalho");
    map.put(Material.SPRUCE_BUTTON, "Botão de pinheiro");
    map.put(Material.BIRCH_BUTTON, "Botão de vidoeiro");
    map.put(Material.JUNGLE_BUTTON, "Botão de selva");
    map.put(Material.ACACIA_BUTTON, "Botão de acácia");
    map.put(Material.DARK_OAK_BUTTON, "Botão de carvalho escuro");
    map.put(Material.MANGROVE_BUTTON, "Botão de mangue");
    map.put(Material.CHERRY_BUTTON, "Botão de cerejeira");
    map.put(Material.PALE_OAK_BUTTON, "Botão de carvalho pálido");
    map.put(Material.BAMBOO_BUTTON, "Botão de bambu");
    map.put(Material.STONE_PRESSURE_PLATE, "Placa de pressão de pedra");
    map.put(Material.OAK_PRESSURE_PLATE, "Placa de pressão de carvalho");
    map.put(Material.SPRUCE_PRESSURE_PLATE, "Placa de pressão de pinheiro");
    map.put(Material.BIRCH_PRESSURE_PLATE, "Placa de pressão de vidoeiro");
    map.put(Material.JUNGLE_PRESSURE_PLATE, "Placa de pressão de selva");
    map.put(Material.ACACIA_PRESSURE_PLATE, "Placa de pressão de acácia");
    map.put(Material.DARK_OAK_PRESSURE_PLATE, "Placa de pressão de carvalho escuro");
    map.put(Material.MANGROVE_PRESSURE_PLATE, "Placa de pressão de mangue");
    map.put(Material.CHERRY_PRESSURE_PLATE, "Placa de pressão de cerejeira");
    map.put(Material.PALE_OAK_PRESSURE_PLATE, "Placa de pressão de carvalho pálido");
    map.put(Material.BAMBOO_PRESSURE_PLATE, "Placa de pressão de bambu");
    map.put(Material.LIGHT_WEIGHTED_PRESSURE_PLATE, "Placa de pressão leve");
    map.put(Material.HEAVY_WEIGHTED_PRESSURE_PLATE, "Placa de pressão pesada");
    map.put(Material.SCULK_SENSOR, "Sensor sculk");
    map.put(Material.CALIBRATED_SCULK_SENSOR, "Sensor sculk calibrado");
    map.put(Material.TARGET, "Alvo");
    map.put(Material.LIGHTNING_ROD, "Para-raios");

    // Food
    map.put(Material.APPLE, "Maçã");
    map.put(Material.GOLDEN_APPLE, "Maçã dourada");
    map.put(Material.ENCHANTED_GOLDEN_APPLE, "Maçã dourada encantada");
    map.put(Material.MELON_SLICE, "Fatia de melancia");
    map.put(Material.GLISTERING_MELON_SLICE, "Fatia de melancia reluzente");
    map.put(Material.SWEET_BERRIES, "Frutas silvestres");
    map.put(Material.GLOW_BERRIES, "Frutas brilhantes");
    map.put(Material.CHORUS_FRUIT, "Fruta chorus");
    map.put(Material.CARROT, "Cenoura");
    map.put(Material.GOLDEN_CARROT, "Cenoura dourada");
    map.put(Material.POTATO, "Batata");
    map.put(Material.BAKED_POTATO, "Batata assada");
    map.put(Material.POISONOUS_POTATO, "Batata venenosa");
    map.put(Material.BEETROOT, "Beterraba");
    map.put(Material.BEETROOT_SOUP, "Sopa de beterraba");
    map.put(Material.BREAD, "Pão");
    map.put(Material.COOKIE, "Biscoito");
    map.put(Material.PUMPKIN_PIE, "Torta de abóbora");
    map.put(Material.CAKE, "Bolo");
    map.put(Material.OMINOUS_BOTTLE, "Garrafa ominosa");

    // Transport
    map.put(Material.MINECART, "Minecart");
    map.put(Material.CHEST_MINECART, "Minecart com baú");
    map.put(Material.FURNACE_MINECART, "Minecart com fornalha");
    map.put(Material.HOPPER_MINECART, "Minecart com funil");
    map.put(Material.TNT_MINECART, "Minecart com TNT");
    map.put(Material.OAK_BOAT, "Barco de carvalho");
    map.put(Material.SPRUCE_BOAT, "Barco de pinheiro");
    map.put(Material.BIRCH_BOAT, "Barco de vidoeiro");
    map.put(Material.JUNGLE_BOAT, "Barco de selva");
    map.put(Material.ACACIA_BOAT, "Barco de acácia");
    map.put(Material.DARK_OAK_BOAT, "Barco de carvalho escuro");
    map.put(Material.MANGROVE_BOAT, "Barco de mangue");
    map.put(Material.CHERRY_BOAT, "Barco de cerejeira");
    map.put(Material.PALE_OAK_BOAT, "Barco de carvalho pálido");
    map.put(Material.BAMBOO_RAFT, "Jangada de bambu");
    map.put(Material.OAK_CHEST_BOAT, "Barco com baú de carvalho");
    map.put(Material.SPRUCE_CHEST_BOAT, "Barco com baú de pinheiro");
    map.put(Material.BIRCH_CHEST_BOAT, "Barco com baú de vidoeiro");
    map.put(Material.JUNGLE_CHEST_BOAT, "Barco com baú de selva");
    map.put(Material.ACACIA_CHEST_BOAT, "Barco com baú de acácia");
    map.put(Material.DARK_OAK_CHEST_BOAT, "Barco com baú de carvalho escuro");
    map.put(Material.MANGROVE_CHEST_BOAT, "Barco com baú de mangue");
    map.put(Material.CHERRY_CHEST_BOAT, "Barco com baú de cerejeira");
    map.put(Material.PALE_OAK_CHEST_BOAT, "Barco com baú de carvalho pálido");
    map.put(Material.BAMBOO_CHEST_RAFT, "Jangada com baú de bambu");
    map.put(Material.RAIL, "Trilho");
    map.put(Material.POWERED_RAIL, "Trilho motorizado");
    map.put(Material.DETECTOR_RAIL, "Trilho detector");
    map.put(Material.ACTIVATOR_RAIL, "Trilho ativador");

    // Storage
    map.put(Material.ENDER_CHEST, "Baú do End");
    map.put(Material.SHULKER_BOX, "Caixa de shulker");
    map.put(Material.WHITE_SHULKER_BOX, "Caixa de shulker branca");
    map.put(Material.ORANGE_SHULKER_BOX, "Caixa de shulker laranja");
    map.put(Material.MAGENTA_SHULKER_BOX, "Caixa de shulker magenta");
    map.put(Material.LIGHT_BLUE_SHULKER_BOX, "Caixa de shulker azul-claro");
    map.put(Material.YELLOW_SHULKER_BOX, "Caixa de shulker amarela");
    map.put(Material.LIME_SHULKER_BOX, "Caixa de shulker verde-limão");
    map.put(Material.PINK_SHULKER_BOX, "Caixa de shulker rosa");
    map.put(Material.GRAY_SHULKER_BOX, "Caixa de shulker cinza");
    map.put(Material.LIGHT_GRAY_SHULKER_BOX, "Caixa de shulker cinza-claro");
    map.put(Material.CYAN_SHULKER_BOX, "Caixa de shulker ciano");
    map.put(Material.PURPLE_SHULKER_BOX, "Caixa de shulker roxa");
    map.put(Material.BLUE_SHULKER_BOX, "Caixa de shulker azul");
    map.put(Material.BROWN_SHULKER_BOX, "Caixa de shulker marrom");
    map.put(Material.GREEN_SHULKER_BOX, "Caixa de shulker verde");
    map.put(Material.RED_SHULKER_BOX, "Caixa de shulker vermelha");
    map.put(Material.BLACK_SHULKER_BOX, "Caixa de shulker preta");
    map.put(Material.BUNDLE, "Pacote");
    map.put(Material.WHITE_BUNDLE, "Pacote branco");
    map.put(Material.ORANGE_BUNDLE, "Pacote laranja");
    map.put(Material.MAGENTA_BUNDLE, "Pacote magenta");
    map.put(Material.LIGHT_BLUE_BUNDLE, "Pacote azul-claro");
    map.put(Material.YELLOW_BUNDLE, "Pacote amarelo");
    map.put(Material.LIME_BUNDLE, "Pacote verde-limão");
    map.put(Material.PINK_BUNDLE, "Pacote rosa");
    map.put(Material.GRAY_BUNDLE, "Pacote cinza");
    map.put(Material.LIGHT_GRAY_BUNDLE, "Pacote cinza-claro");
    map.put(Material.CYAN_BUNDLE, "Pacote ciano");
    map.put(Material.PURPLE_BUNDLE, "Pacote roxo");
    map.put(Material.BLUE_BUNDLE, "Pacote azul");
    map.put(Material.BROWN_BUNDLE, "Pacote marrom");
    map.put(Material.GREEN_BUNDLE, "Pacote verde");
    map.put(Material.RED_BUNDLE, "Pacote vermelho");
    map.put(Material.BLACK_BUNDLE, "Pacote preto");

    // Magic
    map.put(Material.ENCHANTING_TABLE, "Mesa de encantamentos");
    map.put(Material.BREWING_STAND, "Suporte de poções");
    map.put(Material.CAULDRON, "Caldeirão");
    map.put(Material.EXPERIENCE_BOTTLE, "Garrafa de experiência");
    map.put(Material.BLAZE_ROD, "Bastão de blaze");
    map.put(Material.BLAZE_POWDER, "Pó de blaze");
    map.put(Material.MAGMA_CREAM, "Creme de magma");
    map.put(Material.FERMENTED_SPIDER_EYE, "Olho de aranha fermentado");
    map.put(Material.RABBIT_FOOT, "Pé de coelho");
    map.put(Material.PHANTOM_MEMBRANE, "Membrana de phantom");
    map.put(Material.NETHER_STAR, "Estrela do Nether");
    map.put(Material.DRAGON_BREATH, "Bafo de dragão");
    map.put(Material.ENDER_EYE, "Olho do End");
    map.put(Material.FIRE_CHARGE, "Bola de fogo");

    // Nature
    map.put(Material.GRASS_BLOCK, "Bloco de grama");
    map.put(Material.DIRT, "Terra");
    map.put(Material.COARSE_DIRT, "Terra grossa");
    map.put(Material.PODZOL, "Podzol");
    map.put(Material.MYCELIUM, "Micélio");
    map.put(Material.ROOTED_DIRT, "Terra enraizada");
    map.put(Material.MUD, "Lama");
    map.put(Material.CLAY, "Argila");
    map.put(Material.GRAVEL, "Cascalho");
    map.put(Material.SAND, "Areia");
    map.put(Material.RED_SAND, "Areia vermelha");
    map.put(Material.SNOW_BLOCK, "Bloco de neve");
    map.put(Material.ICE, "Gelo");
    map.put(Material.PACKED_ICE, "Gelo compactado");
    map.put(Material.BLUE_ICE, "Gelo azul");
    map.put(Material.OBSIDIAN, "Obsidiana");
    map.put(Material.CRYING_OBSIDIAN, "Obsidiana chorando");
    map.put(Material.BEDROCK, "Rocha base");
    map.put(Material.MOSS_BLOCK, "Bloco de musgo");
    map.put(Material.PALE_MOSS_BLOCK, "Bloco de musgo pálido");
    map.put(Material.SCULK, "Sculk");
    map.put(Material.SCULK_CATALYST, "Catalisador sculk");
    map.put(Material.SCULK_SHRIEKER, "Gritador sculk");
    map.put(Material.SCULK_VEIN, "Veia sculk");

    // Plants
    map.put(Material.OAK_SAPLING, "Muda de carvalho");
    map.put(Material.SPRUCE_SAPLING, "Muda de pinheiro");
    map.put(Material.BIRCH_SAPLING, "Muda de vidoeiro");
    map.put(Material.JUNGLE_SAPLING, "Muda de selva");
    map.put(Material.ACACIA_SAPLING, "Muda de acácia");
    map.put(Material.DARK_OAK_SAPLING, "Muda de carvalho escuro");
    map.put(Material.MANGROVE_PROPAGULE, "Propágulo de mangue");
    map.put(Material.CHERRY_SAPLING, "Muda de cerejeira");
    map.put(Material.PALE_OAK_SAPLING, "Muda de carvalho pálido");
    map.put(Material.OAK_LEAVES, "Folhas de carvalho");
    map.put(Material.SPRUCE_LEAVES, "Folhas de pinheiro");
    map.put(Material.BIRCH_LEAVES, "Folhas de vidoeiro");
    map.put(Material.JUNGLE_LEAVES, "Folhas de selva");
    map.put(Material.ACACIA_LEAVES, "Folhas de acácia");
    map.put(Material.DARK_OAK_LEAVES, "Folhas de carvalho escuro");
    map.put(Material.MANGROVE_LEAVES, "Folhas de mangue");
    map.put(Material.CHERRY_LEAVES, "Folhas de cerejeira");
    map.put(Material.PALE_OAK_LEAVES, "Folhas de carvalho pálido");
    map.put(Material.AZALEA_LEAVES, "Folhas de azaleia");
    map.put(Material.FLOWERING_AZALEA_LEAVES, "Folhas de azaleia florescendo");
    map.put(Material.FLOWERING_AZALEA, "Azaleia florescendo");
    map.put(Material.AZALEA, "Azaleia");
    map.put(Material.CACTUS, "Cacto");
    map.put(Material.SUGAR_CANE, "Cana-de-açúcar");
    map.put(Material.BAMBOO, "Bambu");
    map.put(Material.KELP, "Alga");
    map.put(Material.SEAGRASS, "Capim marinho");
    map.put(Material.LILY_PAD, "Folha de nenúfar");
    map.put(Material.DEAD_BUSH, "Arbusto morto");
    map.put(Material.FERN, "Samambaia");
    map.put(Material.LARGE_FERN, "Samambaia grande");
    map.put(Material.VINE, "Trepadeira");
    map.put(Material.GLOW_LICHEN, "Líquen brilhante");
    map.put(Material.HANGING_ROOTS, "Raízes penduradas");
    map.put(Material.BIG_DRIPLEAF, "Folha-gotejante grande");
    map.put(Material.SMALL_DRIPLEAF, "Folha-gotejante pequena");

    // Flowers
    map.put(Material.POPPY, "Papoula");
    map.put(Material.BLUE_ORCHID, "Orquídea azul");
    map.put(Material.ALLIUM, "Allium");
    map.put(Material.AZURE_BLUET, "Miosótis azul");
    map.put(Material.RED_TULIP, "Tulipa vermelha");
    map.put(Material.ORANGE_TULIP, "Tulipa laranja");
    map.put(Material.WHITE_TULIP, "Tulipa branca");
    map.put(Material.PINK_TULIP, "Tulipa rosa");
    map.put(Material.OXEYE_DAISY, "Margarida");
    map.put(Material.CORNFLOWER, "Centáurea azul");
    map.put(Material.LILY_OF_THE_VALLEY, "Lírio do vale");
    map.put(Material.SUNFLOWER, "Girassol");
    map.put(Material.LILAC, "Lilás");
    map.put(Material.ROSE_BUSH, "Roseira");
    map.put(Material.PEONY, "Peônia");
    map.put(Material.TALL_GRASS, "Capim alto");
    map.put(Material.TORCHFLOWER, "Flor tocha");
    map.put(Material.PITCHER_PLANT, "Planta jarro");
    map.put(Material.OPEN_EYEBLOSSOM, "Flor olho aberta");
    map.put(Material.CLOSED_EYEBLOSSOM, "Flor olho fechada");
    map.put(Material.CHORUS_FLOWER, "Flor chorus");
    map.put(Material.SPORE_BLOSSOM, "Flor de esporo");
    map.put(Material.WITHER_ROSE, "Rosa murcha");
    map.put(Material.PINK_PETALS, "Pétalas rosas");
    map.put(Material.WILDFLOWERS, "Flores silvestres");

    return map;
  }
}
